// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth_attempts.sql

package db

import (
	"context"
	"database/sql"
)

const getRecentAuthAttempts = `-- name: GetRecentAuthAttempts :many
SELECT id, email, success, error_message, attempted_at FROM auth_attempts
WHERE email = ?
ORDER BY attempted_at DESC
LIMIT ?
`

type GetRecentAuthAttemptsParams struct {
	Email string `json:"email"`
	Limit int64  `json:"limit"`
}

func (q *Queries) GetRecentAuthAttempts(ctx context.Context, arg GetRecentAuthAttemptsParams) ([]AuthAttempt, error) {
	rows, err := q.db.QueryContext(ctx, getRecentAuthAttempts, arg.Email, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuthAttempt
	for rows.Next() {
		var i AuthAttempt
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Success,
			&i.ErrorMessage,
			&i.AttemptedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const logAuthAttempt = `-- name: LogAuthAttempt :one
INSERT INTO auth_attempts (email, success, error_message)
VALUES (?, ?, ?)
RETURNING id, email, success, error_message, attempted_at
`

type LogAuthAttemptParams struct {
	Email        string         `json:"email"`
	Success      bool           `json:"success"`
	ErrorMessage sql.NullString `json:"error_message"`
}

func (q *Queries) LogAuthAttempt(ctx context.Context, arg LogAuthAttemptParams) (AuthAttempt, error) {
	row := q.db.QueryRowContext(ctx, logAuthAttempt, arg.Email, arg.Success, arg.ErrorMessage)
	var i AuthAttempt
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Success,
		&i.ErrorMessage,
		&i.AttemptedAt,
	)
	return i, err
}
