// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chat_session_events.sql

package db

import (
	"context"
	"database/sql"
)

const appendChatSessionEvent = `-- name: AppendChatSessionEvent :one
;

INSERT INTO chat_session_events (
session_id,
seq,
event_type,
actor_participant_id,
command_id,
run_id,
payload_json
)
VALUES (
?1,
?2,
?3,
?4,
?5,
?6,
?7
)
RETURNING session_id, seq, event_type, actor_participant_id, command_id, run_id, payload_json, created_at
`

type AppendChatSessionEventParams struct {
	SessionID          string         `json:"session_id"`
	Seq                int64          `json:"seq"`
	EventType          string         `json:"event_type"`
	ActorParticipantID sql.NullString `json:"actor_participant_id"`
	CommandID          sql.NullString `json:"command_id"`
	RunID              sql.NullString `json:"run_id"`
	PayloadJson        string         `json:"payload_json"`
}

func (q *Queries) AppendChatSessionEvent(ctx context.Context, arg AppendChatSessionEventParams) (ChatSessionEvent, error) {
	row := q.db.QueryRowContext(ctx, appendChatSessionEvent,
		arg.SessionID,
		arg.Seq,
		arg.EventType,
		arg.ActorParticipantID,
		arg.CommandID,
		arg.RunID,
		arg.PayloadJson,
	)
	var i ChatSessionEvent
	err := row.Scan(
		&i.SessionID,
		&i.Seq,
		&i.EventType,
		&i.ActorParticipantID,
		&i.CommandID,
		&i.RunID,
		&i.PayloadJson,
		&i.CreatedAt,
	)
	return i, err
}

const createChatSessionBaseline = `-- name: CreateChatSessionBaseline :one
;

INSERT INTO chat_session_baselines (
session_id,
parent_session_id,
forked_from_seq,
baseline_projection_version,
messages_json,
runs_json,
artifacts_json,
participants_json,
topology_json,
selected_state_json
)
VALUES (
?1,
?2,
?3,
?4,
?5,
?6,
?7,
?8,
?9,
?10
)
RETURNING session_id, parent_session_id, forked_from_seq, baseline_projection_version, messages_json, runs_json, artifacts_json, participants_json, topology_json, selected_state_json, created_at
`

type CreateChatSessionBaselineParams struct {
	SessionID                 string `json:"session_id"`
	ParentSessionID           string `json:"parent_session_id"`
	ForkedFromSeq             int64  `json:"forked_from_seq"`
	BaselineProjectionVersion int64  `json:"baseline_projection_version"`
	MessagesJson              string `json:"messages_json"`
	RunsJson                  string `json:"runs_json"`
	ArtifactsJson             string `json:"artifacts_json"`
	ParticipantsJson          string `json:"participants_json"`
	TopologyJson              string `json:"topology_json"`
	SelectedStateJson         string `json:"selected_state_json"`
}

func (q *Queries) CreateChatSessionBaseline(ctx context.Context, arg CreateChatSessionBaselineParams) (ChatSessionBaseline, error) {
	row := q.db.QueryRowContext(ctx, createChatSessionBaseline,
		arg.SessionID,
		arg.ParentSessionID,
		arg.ForkedFromSeq,
		arg.BaselineProjectionVersion,
		arg.MessagesJson,
		arg.RunsJson,
		arg.ArtifactsJson,
		arg.ParticipantsJson,
		arg.TopologyJson,
		arg.SelectedStateJson,
	)
	var i ChatSessionBaseline
	err := row.Scan(
		&i.SessionID,
		&i.ParentSessionID,
		&i.ForkedFromSeq,
		&i.BaselineProjectionVersion,
		&i.MessagesJson,
		&i.RunsJson,
		&i.ArtifactsJson,
		&i.ParticipantsJson,
		&i.TopologyJson,
		&i.SelectedStateJson,
		&i.CreatedAt,
	)
	return i, err
}

const ensureChatSessionSequence = `-- name: EnsureChatSessionSequence :exec
INSERT INTO chat_session_sequences (session_id, next_seq)
VALUES (?1, 1)
ON CONFLICT (session_id) DO NOTHING
`

func (q *Queries) EnsureChatSessionSequence(ctx context.Context, sessionID string) error {
	_, err := q.db.ExecContext(ctx, ensureChatSessionSequence, sessionID)
	return err
}

const getChatSessionBaseline = `-- name: GetChatSessionBaseline :one
;

SELECT session_id, parent_session_id, forked_from_seq, baseline_projection_version, messages_json, runs_json, artifacts_json, participants_json, topology_json, selected_state_json, created_at
FROM chat_session_baselines
WHERE session_id = ?1
`

func (q *Queries) GetChatSessionBaseline(ctx context.Context, sessionID string) (ChatSessionBaseline, error) {
	row := q.db.QueryRowContext(ctx, getChatSessionBaseline, sessionID)
	var i ChatSessionBaseline
	err := row.Scan(
		&i.SessionID,
		&i.ParentSessionID,
		&i.ForkedFromSeq,
		&i.BaselineProjectionVersion,
		&i.MessagesJson,
		&i.RunsJson,
		&i.ArtifactsJson,
		&i.ParticipantsJson,
		&i.TopologyJson,
		&i.SelectedStateJson,
		&i.CreatedAt,
	)
	return i, err
}

const getChatSessionProjection = `-- name: GetChatSessionProjection :one
;

SELECT session_id, last_seq, messages_json, runs_json, participants_json, artifacts_json, topology_json, updated_at
FROM chat_session_projections
WHERE session_id = ?1
`

func (q *Queries) GetChatSessionProjection(ctx context.Context, sessionID string) (ChatSessionProjection, error) {
	row := q.db.QueryRowContext(ctx, getChatSessionProjection, sessionID)
	var i ChatSessionProjection
	err := row.Scan(
		&i.SessionID,
		&i.LastSeq,
		&i.MessagesJson,
		&i.RunsJson,
		&i.ParticipantsJson,
		&i.ArtifactsJson,
		&i.TopologyJson,
		&i.UpdatedAt,
	)
	return i, err
}

const listChatSessionEventsAfter = `-- name: ListChatSessionEventsAfter :many
;

SELECT session_id, seq, event_type, actor_participant_id, command_id, run_id, payload_json, created_at
FROM chat_session_events
WHERE session_id = ?1
AND seq > ?2
ORDER BY seq ASC
LIMIT ?3
`

type ListChatSessionEventsAfterParams struct {
	SessionID string `json:"session_id"`
	AfterSeq  int64  `json:"after_seq"`
	Limit     int64  `json:"limit"`
}

func (q *Queries) ListChatSessionEventsAfter(ctx context.Context, arg ListChatSessionEventsAfterParams) ([]ChatSessionEvent, error) {
	rows, err := q.db.QueryContext(ctx, listChatSessionEventsAfter, arg.SessionID, arg.AfterSeq, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChatSessionEvent
	for rows.Next() {
		var i ChatSessionEvent
		if err := rows.Scan(
			&i.SessionID,
			&i.Seq,
			&i.EventType,
			&i.ActorParticipantID,
			&i.CommandID,
			&i.RunID,
			&i.PayloadJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChatSessionEventsThrough = `-- name: ListChatSessionEventsThrough :many
;

SELECT session_id, seq, event_type, actor_participant_id, command_id, run_id, payload_json, created_at
FROM chat_session_events
WHERE session_id = ?1
AND seq <= ?2
ORDER BY seq ASC
`

type ListChatSessionEventsThroughParams struct {
	SessionID  string `json:"session_id"`
	ThroughSeq int64  `json:"through_seq"`
}

func (q *Queries) ListChatSessionEventsThrough(ctx context.Context, arg ListChatSessionEventsThroughParams) ([]ChatSessionEvent, error) {
	rows, err := q.db.QueryContext(ctx, listChatSessionEventsThrough, arg.SessionID, arg.ThroughSeq)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChatSessionEvent
	for rows.Next() {
		var i ChatSessionEvent
		if err := rows.Scan(
			&i.SessionID,
			&i.Seq,
			&i.EventType,
			&i.ActorParticipantID,
			&i.CommandID,
			&i.RunID,
			&i.PayloadJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reserveChatSessionSeq = `-- name: ReserveChatSessionSeq :one
;

UPDATE chat_session_sequences
SET next_seq = next_seq + 1
WHERE session_id = ?1
RETURNING next_seq - 1 AS seq
`

func (q *Queries) ReserveChatSessionSeq(ctx context.Context, sessionID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, reserveChatSessionSeq, sessionID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const upsertChatSessionProjection = `-- name: UpsertChatSessionProjection :one
;

INSERT INTO chat_session_projections (
session_id,
last_seq,
messages_json,
runs_json,
participants_json,
artifacts_json,
topology_json
)
VALUES (
?1,
?2,
?3,
?4,
?5,
?6,
?7
)
ON CONFLICT (session_id) DO UPDATE SET
last_seq = excluded.last_seq,
messages_json = excluded.messages_json,
runs_json = excluded.runs_json,
participants_json = excluded.participants_json,
artifacts_json = excluded.artifacts_json,
topology_json = excluded.topology_json,
updated_at = CURRENT_TIMESTAMP
RETURNING session_id, last_seq, messages_json, runs_json, participants_json, artifacts_json, topology_json, updated_at
`

type UpsertChatSessionProjectionParams struct {
	SessionID        string `json:"session_id"`
	LastSeq          int64  `json:"last_seq"`
	MessagesJson     string `json:"messages_json"`
	RunsJson         string `json:"runs_json"`
	ParticipantsJson string `json:"participants_json"`
	ArtifactsJson    string `json:"artifacts_json"`
	TopologyJson     string `json:"topology_json"`
}

func (q *Queries) UpsertChatSessionProjection(ctx context.Context, arg UpsertChatSessionProjectionParams) (ChatSessionProjection, error) {
	row := q.db.QueryRowContext(ctx, upsertChatSessionProjection,
		arg.SessionID,
		arg.LastSeq,
		arg.MessagesJson,
		arg.RunsJson,
		arg.ParticipantsJson,
		arg.ArtifactsJson,
		arg.TopologyJson,
	)
	var i ChatSessionProjection
	err := row.Scan(
		&i.SessionID,
		&i.LastSeq,
		&i.MessagesJson,
		&i.RunsJson,
		&i.ParticipantsJson,
		&i.ArtifactsJson,
		&i.TopologyJson,
		&i.UpdatedAt,
	)
	return i, err
}
