// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: impl_workspaces.sql

package db

import (
	"context"
	"database/sql"
	"strings"
)

const clearInvalidImplWorkspacePlanRefs = `-- name: ClearInvalidImplWorkspacePlanRefs :execrows
UPDATE impl_workspaces
SET
    plan_dir_rel = NULL,
    plan_dir = NULL
WHERE
    plan_dir_rel IS NOT NULL
    AND NOT EXISTS (
        SELECT 1
        FROM plan_workspaces
        WHERE plan_workspaces.plan_dir_rel = impl_workspaces.plan_dir_rel
    )
`

func (q *Queries) ClearInvalidImplWorkspacePlanRefs(ctx context.Context) (int64, error) {
	result, err := q.db.ExecContext(ctx, clearInvalidImplWorkspacePlanRefs)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getImplWorkspace = `-- name: GetImplWorkspace :one
SELECT project_id, workspace_slug, checkout_role, checkout_path, display_name, host, url, plan_dir_rel, plan_dir, status, branch, commit_hash, trunk_branch, top_branch, bottom_branch, bottom_parent_branch, base_branch, ahead_count, behind_count, merged_at, cleaned_up_at, merge_evidence, cleanup_proof_kind, cleanup_proof_source_ref, cleanup_proof_target_commit, cleanup_proof_at, cleanup_risk_reason, env_last_repaired_at, env_last_error, git_detail, activity_hash, activity_checked_at, discovered_at, last_discovered_at, updated_at
FROM impl_workspaces
WHERE
    project_id = ?1
    AND workspace_slug = ?2
`

type GetImplWorkspaceParams struct {
	ProjectID     string `json:"project_id"`
	WorkspaceSlug string `json:"workspace_slug"`
}

func (q *Queries) GetImplWorkspace(ctx context.Context, arg GetImplWorkspaceParams) (ImplWorkspace, error) {
	row := q.db.QueryRowContext(ctx, getImplWorkspace, arg.ProjectID, arg.WorkspaceSlug)
	var i ImplWorkspace
	err := row.Scan(
		&i.ProjectID,
		&i.WorkspaceSlug,
		&i.CheckoutRole,
		&i.CheckoutPath,
		&i.DisplayName,
		&i.Host,
		&i.Url,
		&i.PlanDirRel,
		&i.PlanDir,
		&i.Status,
		&i.Branch,
		&i.CommitHash,
		&i.TrunkBranch,
		&i.TopBranch,
		&i.BottomBranch,
		&i.BottomParentBranch,
		&i.BaseBranch,
		&i.AheadCount,
		&i.BehindCount,
		&i.MergedAt,
		&i.CleanedUpAt,
		&i.MergeEvidence,
		&i.CleanupProofKind,
		&i.CleanupProofSourceRef,
		&i.CleanupProofTargetCommit,
		&i.CleanupProofAt,
		&i.CleanupRiskReason,
		&i.EnvLastRepairedAt,
		&i.EnvLastError,
		&i.GitDetail,
		&i.ActivityHash,
		&i.ActivityCheckedAt,
		&i.DiscoveredAt,
		&i.LastDiscoveredAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveImplWorkspaces = `-- name: ListActiveImplWorkspaces :many
SELECT project_id, workspace_slug, checkout_role, checkout_path, display_name, host, url, plan_dir_rel, plan_dir, status, branch, commit_hash, trunk_branch, top_branch, bottom_branch, bottom_parent_branch, base_branch, ahead_count, behind_count, merged_at, cleaned_up_at, merge_evidence, cleanup_proof_kind, cleanup_proof_source_ref, cleanup_proof_target_commit, cleanup_proof_at, cleanup_risk_reason, env_last_repaired_at, env_last_error, git_detail, activity_hash, activity_checked_at, discovered_at, last_discovered_at, updated_at
FROM impl_workspaces
WHERE status = 'active'
ORDER BY LOWER(display_name), project_id, workspace_slug
`

func (q *Queries) ListActiveImplWorkspaces(ctx context.Context) ([]ImplWorkspace, error) {
	rows, err := q.db.QueryContext(ctx, listActiveImplWorkspaces)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ImplWorkspace
	for rows.Next() {
		var i ImplWorkspace
		if err := rows.Scan(
			&i.ProjectID,
			&i.WorkspaceSlug,
			&i.CheckoutRole,
			&i.CheckoutPath,
			&i.DisplayName,
			&i.Host,
			&i.Url,
			&i.PlanDirRel,
			&i.PlanDir,
			&i.Status,
			&i.Branch,
			&i.CommitHash,
			&i.TrunkBranch,
			&i.TopBranch,
			&i.BottomBranch,
			&i.BottomParentBranch,
			&i.BaseBranch,
			&i.AheadCount,
			&i.BehindCount,
			&i.MergedAt,
			&i.CleanedUpAt,
			&i.MergeEvidence,
			&i.CleanupProofKind,
			&i.CleanupProofSourceRef,
			&i.CleanupProofTargetCommit,
			&i.CleanupProofAt,
			&i.CleanupRiskReason,
			&i.EnvLastRepairedAt,
			&i.EnvLastError,
			&i.GitDetail,
			&i.ActivityHash,
			&i.ActivityCheckedAt,
			&i.DiscoveredAt,
			&i.LastDiscoveredAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImplWorkspaces = `-- name: ListImplWorkspaces :many
SELECT project_id, workspace_slug, checkout_role, checkout_path, display_name, host, url, plan_dir_rel, plan_dir, status, branch, commit_hash, trunk_branch, top_branch, bottom_branch, bottom_parent_branch, base_branch, ahead_count, behind_count, merged_at, cleaned_up_at, merge_evidence, cleanup_proof_kind, cleanup_proof_source_ref, cleanup_proof_target_commit, cleanup_proof_at, cleanup_risk_reason, env_last_repaired_at, env_last_error, git_detail, activity_hash, activity_checked_at, discovered_at, last_discovered_at, updated_at
FROM impl_workspaces
WHERE
    CAST(?1 AS TEXT) = ''
    OR project_id = CAST(?1 AS TEXT)
ORDER BY
    status = 'active' DESC,
    updated_at DESC,
    LOWER(display_name),
    project_id,
    workspace_slug
`

func (q *Queries) ListImplWorkspaces(ctx context.Context, projectID string) ([]ImplWorkspace, error) {
	rows, err := q.db.QueryContext(ctx, listImplWorkspaces, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ImplWorkspace
	for rows.Next() {
		var i ImplWorkspace
		if err := rows.Scan(
			&i.ProjectID,
			&i.WorkspaceSlug,
			&i.CheckoutRole,
			&i.CheckoutPath,
			&i.DisplayName,
			&i.Host,
			&i.Url,
			&i.PlanDirRel,
			&i.PlanDir,
			&i.Status,
			&i.Branch,
			&i.CommitHash,
			&i.TrunkBranch,
			&i.TopBranch,
			&i.BottomBranch,
			&i.BottomParentBranch,
			&i.BaseBranch,
			&i.AheadCount,
			&i.BehindCount,
			&i.MergedAt,
			&i.CleanedUpAt,
			&i.MergeEvidence,
			&i.CleanupProofKind,
			&i.CleanupProofSourceRef,
			&i.CleanupProofTargetCommit,
			&i.CleanupProofAt,
			&i.CleanupRiskReason,
			&i.EnvLastRepairedAt,
			&i.EnvLastError,
			&i.GitDetail,
			&i.ActivityHash,
			&i.ActivityCheckedAt,
			&i.DiscoveredAt,
			&i.LastDiscoveredAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllActiveImplWorkspacesCleanedUp = `-- name: MarkAllActiveImplWorkspacesCleanedUp :execrows
;

UPDATE impl_workspaces
SET status = 'cleaned_up',
cleaned_up_at = CURRENT_TIMESTAMP,
updated_at = CURRENT_TIMESTAMP
WHERE status = 'active'
`

func (q *Queries) MarkAllActiveImplWorkspacesCleanedUp(ctx context.Context) (int64, error) {
	result, err := q.db.ExecContext(ctx, markAllActiveImplWorkspacesCleanedUp)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markImplWorkspaceCleanedUp = `-- name: MarkImplWorkspaceCleanedUp :execrows
;

UPDATE impl_workspaces
SET status = 'cleaned_up',
cleaned_up_at = CURRENT_TIMESTAMP,
updated_at = CURRENT_TIMESTAMP
WHERE project_id = ?1
AND workspace_slug = ?2
AND status IN ('active', 'merged')
`

type MarkImplWorkspaceCleanedUpParams struct {
	ProjectID     string `json:"project_id"`
	WorkspaceSlug string `json:"workspace_slug"`
}

func (q *Queries) MarkImplWorkspaceCleanedUp(ctx context.Context, arg MarkImplWorkspaceCleanedUpParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markImplWorkspaceCleanedUp, arg.ProjectID, arg.WorkspaceSlug)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markImplWorkspaceMergeUnknown = `-- name: MarkImplWorkspaceMergeUnknown :execrows
;

UPDATE impl_workspaces
SET cleanup_proof_kind = 'unknown',
cleanup_proof_source_ref = ?1,
cleanup_proof_target_commit = NULL,
cleanup_proof_at = NULL,
cleanup_risk_reason = ?2,
merge_evidence = ?3
WHERE project_id = ?4
AND workspace_slug = ?5
`

type MarkImplWorkspaceMergeUnknownParams struct {
	CleanupProofSourceRef sql.NullString `json:"cleanup_proof_source_ref"`
	CleanupRiskReason     sql.NullString `json:"cleanup_risk_reason"`
	MergeEvidence         sql.NullString `json:"merge_evidence"`
	ProjectID             string         `json:"project_id"`
	WorkspaceSlug         string         `json:"workspace_slug"`
}

func (q *Queries) MarkImplWorkspaceMergeUnknown(ctx context.Context, arg MarkImplWorkspaceMergeUnknownParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markImplWorkspaceMergeUnknown,
		arg.CleanupProofSourceRef,
		arg.CleanupRiskReason,
		arg.MergeEvidence,
		arg.ProjectID,
		arg.WorkspaceSlug,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markImplWorkspaceMerged = `-- name: MarkImplWorkspaceMerged :execrows
;

UPDATE impl_workspaces
SET status = 'merged',
merged_at = CURRENT_TIMESTAMP,
merge_evidence = ?1,
cleanup_proof_kind = COALESCE (NULLIF (?2,
''),
'unknown'),
cleanup_proof_source_ref = ?3,
cleanup_proof_target_commit = ?4,
cleanup_proof_at = CURRENT_TIMESTAMP,
cleanup_risk_reason = NULL,
updated_at = CURRENT_TIMESTAMP
WHERE project_id = ?5
AND workspace_slug = ?6
`

type MarkImplWorkspaceMergedParams struct {
	MergeEvidence            sql.NullString `json:"merge_evidence"`
	CleanupProofKind         interface{}    `json:"cleanup_proof_kind"`
	CleanupProofSourceRef    sql.NullString `json:"cleanup_proof_source_ref"`
	CleanupProofTargetCommit sql.NullString `json:"cleanup_proof_target_commit"`
	ProjectID                string         `json:"project_id"`
	WorkspaceSlug            string         `json:"workspace_slug"`
}

func (q *Queries) MarkImplWorkspaceMerged(ctx context.Context, arg MarkImplWorkspaceMergedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markImplWorkspaceMerged,
		arg.MergeEvidence,
		arg.CleanupProofKind,
		arg.CleanupProofSourceRef,
		arg.CleanupProofTargetCommit,
		arg.ProjectID,
		arg.WorkspaceSlug,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markMissingImplWorkspacesCleanedUp = `-- name: MarkMissingImplWorkspacesCleanedUp :execrows
;

UPDATE impl_workspaces
SET status = 'cleaned_up',
cleaned_up_at = CURRENT_TIMESTAMP,
updated_at = CURRENT_TIMESTAMP
WHERE status = 'active'
AND workspace_slug NOT IN (/*SLICE:workspace_slugs*/?)
`

func (q *Queries) MarkMissingImplWorkspacesCleanedUp(ctx context.Context, workspaceSlugs []string) (int64, error) {
	query := markMissingImplWorkspacesCleanedUp
	var queryParams []interface{}
	if len(workspaceSlugs) > 0 {
		for _, v := range workspaceSlugs {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:workspace_slugs*/?", strings.Repeat(",?", len(workspaceSlugs))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:workspace_slugs*/?", "NULL", 1)
	}
	result, err := q.db.ExecContext(ctx, query, queryParams...)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const reassignImplWorkspaceCheckoutPathIdentity = `-- name: ReassignImplWorkspaceCheckoutPathIdentity :execrows
;

UPDATE impl_workspaces
SET project_id = ?1,
workspace_slug = ?2
WHERE impl_workspaces.checkout_path = ?3
AND NOT (project_id = ?1 AND workspace_slug = ?2)
AND NOT EXISTS (
SELECT 1
FROM impl_workspaces target
WHERE target.project_id = ?1
AND target.workspace_slug = ?2
)
`

type ReassignImplWorkspaceCheckoutPathIdentityParams struct {
	ProjectID     string `json:"project_id"`
	WorkspaceSlug string `json:"workspace_slug"`
	CheckoutPath  string `json:"checkout_path"`
}

func (q *Queries) ReassignImplWorkspaceCheckoutPathIdentity(ctx context.Context, arg ReassignImplWorkspaceCheckoutPathIdentityParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, reassignImplWorkspaceCheckoutPathIdentity, arg.ProjectID, arg.WorkspaceSlug, arg.CheckoutPath)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const recordImplWorkspaceEnvError = `-- name: RecordImplWorkspaceEnvError :exec
;

UPDATE impl_workspaces
SET env_last_error = ?1
WHERE project_id = ?2
AND workspace_slug = ?3
`

type RecordImplWorkspaceEnvErrorParams struct {
	EnvLastError  sql.NullString `json:"env_last_error"`
	ProjectID     string         `json:"project_id"`
	WorkspaceSlug string         `json:"workspace_slug"`
}

func (q *Queries) RecordImplWorkspaceEnvError(ctx context.Context, arg RecordImplWorkspaceEnvErrorParams) error {
	_, err := q.db.ExecContext(ctx, recordImplWorkspaceEnvError, arg.EnvLastError, arg.ProjectID, arg.WorkspaceSlug)
	return err
}

const recordImplWorkspaceEnvRepair = `-- name: RecordImplWorkspaceEnvRepair :exec
;

UPDATE impl_workspaces
SET env_last_repaired_at = CURRENT_TIMESTAMP,
env_last_error = NULL
WHERE project_id = ?1
AND workspace_slug = ?2
`

type RecordImplWorkspaceEnvRepairParams struct {
	ProjectID     string `json:"project_id"`
	WorkspaceSlug string `json:"workspace_slug"`
}

func (q *Queries) RecordImplWorkspaceEnvRepair(ctx context.Context, arg RecordImplWorkspaceEnvRepairParams) error {
	_, err := q.db.ExecContext(ctx, recordImplWorkspaceEnvRepair, arg.ProjectID, arg.WorkspaceSlug)
	return err
}

const repairProtectedImplWorkspaceTerminalStatuses = `-- name: RepairProtectedImplWorkspaceTerminalStatuses :execrows
UPDATE impl_workspaces
SET
    status = 'active',
    merged_at = NULL,
    cleaned_up_at = NULL,
    merge_evidence = NULL,
    cleanup_proof_kind = 'unknown',
    cleanup_proof_source_ref = NULL,
    cleanup_proof_target_commit = NULL,
    cleanup_proof_at = NULL,
    cleanup_risk_reason = NULL,
    updated_at = CURRENT_TIMESTAMP
WHERE
    (
        CAST(?1 AS TEXT) = ''
        OR project_id = CAST(?1 AS TEXT)
    )
    AND (
        workspace_slug IN ('main', 'stage')
        OR checkout_role IN ('main', 'stage')
    )
    AND status IN ('merged', 'cleaned_up')
`

func (q *Queries) RepairProtectedImplWorkspaceTerminalStatuses(ctx context.Context, projectID string) (int64, error) {
	result, err := q.db.ExecContext(ctx, repairProtectedImplWorkspaceTerminalStatuses, projectID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertDiscoveredImplWorkspace = `-- name: UpsertDiscoveredImplWorkspace :one
INSERT INTO impl_workspaces (
    project_id,
    workspace_slug,
    checkout_role,
    checkout_path,
    display_name,
    host,
    url,
    plan_dir_rel,
    plan_dir,
    status,
    merged_at,
    merge_evidence,
    cleanup_proof_kind,
    cleanup_proof_source_ref,
    cleanup_proof_target_commit,
    cleanup_proof_at,
    cleanup_risk_reason,
    branch,
    commit_hash,
    trunk_branch,
    top_branch,
    bottom_branch,
    bottom_parent_branch,
    base_branch,
    ahead_count,
    behind_count,
    git_detail,
    activity_hash
)
VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7,
    ?8,
    ?9,
    ?10,
    (
        CASE
            WHEN ?10 = 'merged' THEN CURRENT_TIMESTAMP ELSE NULL
        END
    ),
    ?11,
    COALESCE(NULLIF(?12, ''), 'unknown'),
    ?13,
    ?14,
    ?15,
    ?16,
    ?17,
    ?18,
    ?19,
    ?20,
    ?21,
    ?22,
    ?23,
    ?24,
    ?25,
    ?26,
    ?27
)
ON CONFLICT (project_id, workspace_slug) DO UPDATE SET
checkout_role = excluded.checkout_role,
checkout_path = excluded.checkout_path,
display_name = excluded.display_name,
host = excluded.host,
url = excluded.url,
plan_dir_rel = excluded.plan_dir_rel,
plan_dir = excluded.plan_dir,
status = excluded.status,
merged_at = (CASE
WHEN excluded.status = 'merged'
AND (
impl_workspaces.status IS NOT excluded.status
OR COALESCE (impl_workspaces.merge_evidence,
'') IS NOT COALESCE (excluded.merge_evidence,
'')
) THEN CURRENT_TIMESTAMP
WHEN excluded.status = 'merged' THEN impl_workspaces.merged_at
ELSE NULL
END),
merge_evidence = (CASE
WHEN excluded.status = 'merged' THEN excluded.merge_evidence
ELSE NULL
END),
cleanup_proof_kind = excluded.cleanup_proof_kind,
cleanup_proof_source_ref = excluded.cleanup_proof_source_ref,
cleanup_proof_target_commit = excluded.cleanup_proof_target_commit,
cleanup_proof_at = excluded.cleanup_proof_at,
cleanup_risk_reason = excluded.cleanup_risk_reason,
branch = excluded.branch,
commit_hash = excluded.commit_hash,
trunk_branch = excluded.trunk_branch,
top_branch = excluded.top_branch,
bottom_branch = excluded.bottom_branch,
bottom_parent_branch = excluded.bottom_parent_branch,
base_branch = excluded.base_branch,
ahead_count = excluded.ahead_count,
behind_count = excluded.behind_count,
git_detail = excluded.git_detail,
last_discovered_at = CURRENT_TIMESTAMP,
activity_checked_at = CURRENT_TIMESTAMP,
updated_at = CASE
WHEN impl_workspaces.status IS NOT excluded.status THEN CURRENT_TIMESTAMP
WHEN COALESCE (impl_workspaces.activity_hash,
'') = '' THEN impl_workspaces.updated_at
WHEN COALESCE (impl_workspaces.activity_hash,
'') IS NOT COALESCE (excluded.activity_hash,
'') THEN CURRENT_TIMESTAMP
ELSE impl_workspaces.updated_at
END,
activity_hash = excluded.activity_hash
RETURNING project_id, workspace_slug, checkout_role, checkout_path, display_name, host, url, plan_dir_rel, plan_dir, status, branch, commit_hash, trunk_branch, top_branch, bottom_branch, bottom_parent_branch, base_branch, ahead_count, behind_count, merged_at, cleaned_up_at, merge_evidence, cleanup_proof_kind, cleanup_proof_source_ref, cleanup_proof_target_commit, cleanup_proof_at, cleanup_risk_reason, env_last_repaired_at, env_last_error, git_detail, activity_hash, activity_checked_at, discovered_at, last_discovered_at, updated_at
`

type UpsertDiscoveredImplWorkspaceParams struct {
	ProjectID                string         `json:"project_id"`
	WorkspaceSlug            string         `json:"workspace_slug"`
	CheckoutRole             string         `json:"checkout_role"`
	CheckoutPath             string         `json:"checkout_path"`
	DisplayName              string         `json:"display_name"`
	Host                     string         `json:"host"`
	Url                      string         `json:"url"`
	PlanDirRel               sql.NullString `json:"plan_dir_rel"`
	PlanDir                  sql.NullString `json:"plan_dir"`
	Status                   string         `json:"status"`
	MergeEvidence            sql.NullString `json:"merge_evidence"`
	CleanupProofKind         interface{}    `json:"cleanup_proof_kind"`
	CleanupProofSourceRef    sql.NullString `json:"cleanup_proof_source_ref"`
	CleanupProofTargetCommit sql.NullString `json:"cleanup_proof_target_commit"`
	CleanupProofAt           sql.NullTime   `json:"cleanup_proof_at"`
	CleanupRiskReason        sql.NullString `json:"cleanup_risk_reason"`
	Branch                   sql.NullString `json:"branch"`
	CommitHash               sql.NullString `json:"commit_hash"`
	TrunkBranch              sql.NullString `json:"trunk_branch"`
	TopBranch                sql.NullString `json:"top_branch"`
	BottomBranch             sql.NullString `json:"bottom_branch"`
	BottomParentBranch       sql.NullString `json:"bottom_parent_branch"`
	BaseBranch               sql.NullString `json:"base_branch"`
	AheadCount               int64          `json:"ahead_count"`
	BehindCount              int64          `json:"behind_count"`
	GitDetail                sql.NullString `json:"git_detail"`
	ActivityHash             string         `json:"activity_hash"`
}

func (q *Queries) UpsertDiscoveredImplWorkspace(ctx context.Context, arg UpsertDiscoveredImplWorkspaceParams) (ImplWorkspace, error) {
	row := q.db.QueryRowContext(ctx, upsertDiscoveredImplWorkspace,
		arg.ProjectID,
		arg.WorkspaceSlug,
		arg.CheckoutRole,
		arg.CheckoutPath,
		arg.DisplayName,
		arg.Host,
		arg.Url,
		arg.PlanDirRel,
		arg.PlanDir,
		arg.Status,
		arg.MergeEvidence,
		arg.CleanupProofKind,
		arg.CleanupProofSourceRef,
		arg.CleanupProofTargetCommit,
		arg.CleanupProofAt,
		arg.CleanupRiskReason,
		arg.Branch,
		arg.CommitHash,
		arg.TrunkBranch,
		arg.TopBranch,
		arg.BottomBranch,
		arg.BottomParentBranch,
		arg.BaseBranch,
		arg.AheadCount,
		arg.BehindCount,
		arg.GitDetail,
		arg.ActivityHash,
	)
	var i ImplWorkspace
	err := row.Scan(
		&i.ProjectID,
		&i.WorkspaceSlug,
		&i.CheckoutRole,
		&i.CheckoutPath,
		&i.DisplayName,
		&i.Host,
		&i.Url,
		&i.PlanDirRel,
		&i.PlanDir,
		&i.Status,
		&i.Branch,
		&i.CommitHash,
		&i.TrunkBranch,
		&i.TopBranch,
		&i.BottomBranch,
		&i.BottomParentBranch,
		&i.BaseBranch,
		&i.AheadCount,
		&i.BehindCount,
		&i.MergedAt,
		&i.CleanedUpAt,
		&i.MergeEvidence,
		&i.CleanupProofKind,
		&i.CleanupProofSourceRef,
		&i.CleanupProofTargetCommit,
		&i.CleanupProofAt,
		&i.CleanupRiskReason,
		&i.EnvLastRepairedAt,
		&i.EnvLastError,
		&i.GitDetail,
		&i.ActivityHash,
		&i.ActivityCheckedAt,
		&i.DiscoveredAt,
		&i.LastDiscoveredAt,
		&i.UpdatedAt,
	)
	return i, err
}
