// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_preferences.sql

package db

import (
	"context"
)

const getUserPreferences = `-- name: GetUserPreferences :one
SELECT user_email, theme, syntax_theme, created_at, updated_at FROM user_preferences
WHERE user_email = ?
LIMIT 1
`

func (q *Queries) GetUserPreferences(ctx context.Context, userEmail string) (UserPreference, error) {
	row := q.db.QueryRowContext(ctx, getUserPreferences, userEmail)
	var i UserPreference
	err := row.Scan(
		&i.UserEmail,
		&i.Theme,
		&i.SyntaxTheme,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSyntaxTheme = `-- name: UpdateSyntaxTheme :one
INSERT INTO user_preferences (user_email, theme, syntax_theme)
VALUES (?, 'dark', ?)
ON CONFLICT(user_email) DO UPDATE SET
    syntax_theme = excluded.syntax_theme,
    updated_at = CURRENT_TIMESTAMP
RETURNING user_email, theme, syntax_theme, created_at, updated_at
`

type UpdateSyntaxThemeParams struct {
	UserEmail   string `json:"user_email"`
	SyntaxTheme string `json:"syntax_theme"`
}

func (q *Queries) UpdateSyntaxTheme(ctx context.Context, arg UpdateSyntaxThemeParams) (UserPreference, error) {
	row := q.db.QueryRowContext(ctx, updateSyntaxTheme, arg.UserEmail, arg.SyntaxTheme)
	var i UserPreference
	err := row.Scan(
		&i.UserEmail,
		&i.Theme,
		&i.SyntaxTheme,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTheme = `-- name: UpdateTheme :one
INSERT INTO user_preferences (user_email, theme, syntax_theme)
VALUES (?, ?, 'github-dark')
ON CONFLICT(user_email) DO UPDATE SET
    theme = excluded.theme,
    updated_at = CURRENT_TIMESTAMP
RETURNING user_email, theme, syntax_theme, created_at, updated_at
`

type UpdateThemeParams struct {
	UserEmail string `json:"user_email"`
	Theme     string `json:"theme"`
}

func (q *Queries) UpdateTheme(ctx context.Context, arg UpdateThemeParams) (UserPreference, error) {
	row := q.db.QueryRowContext(ctx, updateTheme, arg.UserEmail, arg.Theme)
	var i UserPreference
	err := row.Scan(
		&i.UserEmail,
		&i.Theme,
		&i.SyntaxTheme,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUserPreferences = `-- name: UpsertUserPreferences :one
INSERT INTO user_preferences (user_email, theme, syntax_theme)
VALUES (?, ?, ?)
ON CONFLICT(user_email) DO UPDATE SET
    theme = excluded.theme,
    syntax_theme = excluded.syntax_theme,
    updated_at = CURRENT_TIMESTAMP
RETURNING user_email, theme, syntax_theme, created_at, updated_at
`

type UpsertUserPreferencesParams struct {
	UserEmail   string `json:"user_email"`
	Theme       string `json:"theme"`
	SyntaxTheme string `json:"syntax_theme"`
}

func (q *Queries) UpsertUserPreferences(ctx context.Context, arg UpsertUserPreferencesParams) (UserPreference, error) {
	row := q.db.QueryRowContext(ctx, upsertUserPreferences, arg.UserEmail, arg.Theme, arg.SyntaxTheme)
	var i UserPreference
	err := row.Scan(
		&i.UserEmail,
		&i.Theme,
		&i.SyntaxTheme,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
