// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package pickleball

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"strconv"

	"github.com/CoreyCole/vamos/server/layouts"
	"github.com/CoreyCole/vamos/server/layouts/workbench"
	"github.com/CoreyCole/vamos/server/services/applets"
)

func Page(vm PickleballViewModel) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div id=\"pickleball-app\" class=\"h-full min-h-0 overflow-hidden\" data-init=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs("@get('/examples/pickleball/state?session=" + vm.SessionID + "')")
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `server/services/examples/pickleball/page.templ`, Line: 17, Col: 143}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = workbench.Workbench(buildPickleballWorkbench(vm)).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = layouts.Root(layouts.RootArgs{
			Title:      "Pickleball Self-Modifying App",
			ShowHeader: true,
			PageType:   layouts.PageTypeAgentChat,
		}).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func buildPickleballWorkbench(vm PickleballViewModel) workbench.WorkbenchState {
	return applets.BuildWorkbenchState(nil, applets.WorkbenchState{
		Config: applets.AppletConfig{
			ID:          "pickleball",
			DisplayName: "Pickleball",
			UserLabels: applets.AppletLabels{
				FilesTitle: "Files",
				ChatTitle:  "Chat",
			},
		},
		Files: applets.FilesViewModel{
			Title:     "Files",
			Component: StatePanel(vm),
		},
		Chat: applets.ChatViewModel{
			Title:     "Chat",
			Component: ChatToModifyPanel(vm),
		},
	})
}

func stateLabel(state AppState) string {
	switch state {
	case AppStateGenerating:
		return "Generating"
	case AppStateBuilding:
		return "Building"
	case AppStateSucceeded:
		return "Ready"
	case AppStateFailed:
		return "Needs prompt"
	default:
		return "Idle"
	}
}

func stateChipClass(state AppState) string {
	base := "inline-flex w-fit items-center rounded-full px-3 py-1 text-xs font-semibold uppercase tracking-wide"
	switch state {
	case AppStateGenerating, AppStateBuilding:
		return base + " bg-blue-100 text-blue-700 dark:bg-blue-950 dark:text-blue-200"
	case AppStateSucceeded:
		return base + " bg-emerald-100 text-emerald-700 dark:bg-emerald-950 dark:text-emerald-200"
	case AppStateFailed:
		return base + " bg-destructive/10 text-destructive"
	default:
		return base + " bg-muted text-muted-foreground"
	}
}

func jsString(value string) string {
	return strconv.Quote(value)
}

var _ = templruntime.GeneratedTemplate
